# Change these first
owner: tquizzle # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: TravisQ.com
    url: https://travisq.com
  - name: Q Industries
    url: https://qindustries.llc
  - name: vTechify
    url: https://vtechify.com
  - name: SilasQ.com
    url: https://silasq.com
  - name: VivianQ.com
    url: https://vivianq.com
  - name: Mr. Starry
    url: https://mrstarry.com
  - name: Cloverstitch
    url: https://cloverstitch.com
  - name: The End
    url: https://shoptheend.com
  - name: DJ TQ
    url: https://djtq.me
  - name: Google
    url: https://www.google.com
  - name: Instagram.com
    url: https://instagram.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Short url
    url: https://0hq.cc
  - name: CheapIPTV
    url: https://cheapiptv.org

## DNS Checks
  - name: Google DNS 1
    url: 8.8.4.4
    check: "tcp-ping"
    port: 53
  - name: Google DNS 2
    url: 8.8.8.8
    check: "tcp-ping"
    port: 53
  - name: Cloudflare DNS
    url: 1.1.1.1
    check: "tcp-ping"
    port: 53
  - name: Quad Nine
    url: 9.9.9.9
    check: "tcp-ping"
    port: 53
  - name: NextDNS 1
    url: 45.90.28.207
    check: "tcp-ping"
    port: 53
  - name: NextDNS 2
    url: 45.90.30.207
    check: "tcp-ping"
    port: 53
#  - name: AdGuard Home
#    url: 10.0.1.
#    check: "tcp-ping"
#    port: 53

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.travisq.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://travisq.com/images/travisq-logo-400x400.png
  name: Upptime - TravisQ.com
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a **real** status page which uses **real-time** data from the repo. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  robotsText: "User-agent: * \n Disallow: /"
  
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Back to TravisQ.com
      href: https://travisq.com

# Custom Commit Msgs
commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@travisq.com"

# Schedule Workflows
workflowSchedule:
  graphs: "0 0/12 * * *"
  responseTime: "0 23/4 * * *"
  staticSite: "0 */6 * * *"
  summary: "0 * * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# User-agent
user-agent: tquizzle

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
